#!/usr/bin/env python3
"""Generate out/board_pinmap_fpv.h (REFERENCE header) from design.py.

The FPV AIO firmware port is not started; this header documents the pin
assignment for it WITHOUT touching the Fr4n7 build in firmware/. When the
port lands (outputs_dshot.c + crsf_task.c — see fpv85/DESIGN.md), point the
board component at this header.

design.PINMAP is the single source; edit it, re-run, commit both.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "out", "board_pinmap_fpv.h")

sys.path.insert(0, HERE)
import design  # noqa: E402


def gpio_num(sig):
    return int(sig.replace("GPIO", ""))


def main():
    p = design.PINMAP
    lines = [
        "/* board_pinmap_fpv.h — GENERATED by hardware/pcb_fpv/scripts/gen_pinmap.py.",
        " * STRATOS FPV AIO pin map (design.py PINMAP) — REFERENCE ONLY for now:",
        " * the DShot/CRSF firmware port is specified, not implemented.",
        " * Do not edit by hand; edit design.py and re-run the generator.",
        " * SPDX-License-Identifier: MIT */",
        "#ifndef BOARD_PINMAP_FPV_H",
        "#define BOARD_PINMAP_FPV_H",
        "",
        "/* SPI bus (ICM-42688-P IMU) */",
        f"#define PIN_SPI_SCLK   {gpio_num(p['SPI_SCLK'])}",
        f"#define PIN_SPI_MOSI   {gpio_num(p['SPI_MOSI'])}",
        f"#define PIN_SPI_MISO   {gpio_num(p['SPI_MISO'])}",
        f"#define PIN_CS_IMU     {gpio_num(p['CS_IMU'])}",
        f"#define PIN_IMU_INT    {gpio_num(p['IMU_INT'])}",
        "",
        "/* I2C bus (SPL06-001 0x76 + camera SCCB) */",
        f"#define PIN_I2C_SDA    {gpio_num(p['I2C_SDA'])}",
        f"#define PIN_I2C_SCL    {gpio_num(p['I2C_SCL'])}",
        "",
        "/* motors M1 FR, M2 BR, M3 BL, M4 FL (fc_core mixer) — DShot600 on RMT",
        " * (spec'd, not implemented; same pins as the Fr4n7 brushed PWM) */",
        f"#define PIN_MOTOR_1    {gpio_num(p['MOTOR_1'])}",
        f"#define PIN_MOTOR_2    {gpio_num(p['MOTOR_2'])}",
        f"#define PIN_MOTOR_3    {gpio_num(p['MOTOR_3'])}",
        f"#define PIN_MOTOR_4    {gpio_num(p['MOTOR_4'])}",
        "",
        "/* ExpressLRS CRSF UART (420 kbaud) + VTX SmartAudio — NEW on this board */",
        f"#define PIN_CRSF_TX    {gpio_num(p['CRSF_TX'])}",
        f"#define PIN_CRSF_RX    {gpio_num(p['CRSF_RX'])}",
        f"#define PIN_VTX_SA     {gpio_num(p['VTX_SA'])}",
        "",
        "/* battery sense: 200k/100k divider (2S /3 — VERIFY ADC unit/channel) */",
        f"#define PIN_VBAT_ADC     {gpio_num(p['VBAT_ADC'])}",
        "#define VBAT_ADC_UNIT    ADC_UNIT_1",
        "#define VBAT_ADC_CHANNEL ADC_CHANNEL_4",
        "#define VBAT_DIVIDER     3.0f   /* 2x100k top, 100k bottom */",
        "",
        "/* misc */",
        f"#define PIN_WS2812     {gpio_num(p['WS2812'])}",
        f"#define PIN_CAM_PWDN   {gpio_num(p['CAM_PWDN'])}",
        "",
        "/* SDIO link to ESP32-C6 (esp-hosted) — also set in sdkconfig */",
        f"#define PIN_SDIO_CLK   {gpio_num(p['SDIO_CLK'])}",
        f"#define PIN_SDIO_CMD   {gpio_num(p['SDIO_CMD'])}",
        f"#define PIN_SDIO_D0    {gpio_num(p['SDIO_D0'])}",
        f"#define PIN_SDIO_D1    {gpio_num(p['SDIO_D1'])}",
        f"#define PIN_SDIO_D2    {gpio_num(p['SDIO_D2'])}",
        f"#define PIN_SDIO_D3    {gpio_num(p['SDIO_D3'])}",
        f"#define PIN_C6_EN      {gpio_num(p['C6_EN'])}",
        "",
        "/* UART0 console + BOOT strap (VERIFY inherited from Fr4n7 ledger) */",
        f"#define PIN_UART0_TX   {gpio_num(p['UART0_TX'])}",
        f"#define PIN_UART0_RX   {gpio_num(p['UART0_RX'])}",
        f"#define PIN_BOOT_STRAP {gpio_num(p['BOOT_STRAP'])}",
        "",
        "#endif",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
