#!/usr/bin/env python3
"""Generate firmware/components/board/include/board_pinmap.h from design.py.

The PCB net assignment and the firmware GPIO macros must never drift apart.
design.PINMAP is the single source; this emits the C header the firmware
compiles against. Run after changing PINMAP, and commit both.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(REPO, "firmware", "components", "board", "include", "board_pinmap.h")

sys.path.insert(0, HERE)
import design  # noqa: E402


def gpio_num(sig):
    # "GPIO45" -> 45
    return int(sig.replace("GPIO", ""))


def main():
    p = design.PINMAP
    lines = [
        "/* board_pinmap.h — GENERATED by hardware/pcb/scripts/gen_pinmap.py.",
        " * Mirrors the PCB net assignment (design.py PINMAP) for ESP32-P4 rev A.",
        " * Do not edit by hand; edit design.py and re-run the generator.",
        " * SPDX-License-Identifier: MIT */",
        "#ifndef BOARD_PINMAP_H",
        "#define BOARD_PINMAP_H",
        "",
        "/* SPI bus (ICM-42688-P + PMW3901) */",
        f"#define PIN_SPI_SCLK   {gpio_num(p['SPI_SCLK'])}",
        f"#define PIN_SPI_MOSI   {gpio_num(p['SPI_MOSI'])}",
        f"#define PIN_SPI_MISO   {gpio_num(p['SPI_MISO'])}",
        f"#define PIN_CS_IMU     {gpio_num(p['CS_IMU'])}",
        f"#define PIN_CS_FLOW    {gpio_num(p['CS_FLOW'])}",
        f"#define PIN_IMU_INT    {gpio_num(p['IMU_INT'])}",
        "",
        "/* I2C bus (SPL06-001 0x76, VL53L1X 0x29, camera SCCB) */",
        f"#define PIN_I2C_SDA    {gpio_num(p['I2C_SDA'])}",
        f"#define PIN_I2C_SCL    {gpio_num(p['I2C_SCL'])}",
        f"#define PIN_VL53_XSHUT {gpio_num(p['VL53_XSHUT'])}",
        "",
        "/* motors (M1 FR, M2 BR, M3 BL, M4 FL — see fc_core mixer) */",
        f"#define PIN_MOTOR_1    {gpio_num(p['MOTOR_1'])}",
        f"#define PIN_MOTOR_2    {gpio_num(p['MOTOR_2'])}",
        f"#define PIN_MOTOR_3    {gpio_num(p['MOTOR_3'])}",
        f"#define PIN_MOTOR_4    {gpio_num(p['MOTOR_4'])}",
        "",
        "/* battery sense: 100k/100k divider (VERIFY ADC unit/channel for GPIO%d) */"
        % gpio_num(p["VBAT_ADC"]),
        f"#define PIN_VBAT_ADC     {gpio_num(p['VBAT_ADC'])}",
        "#define VBAT_ADC_UNIT    ADC_UNIT_1",
        "#define VBAT_ADC_CHANNEL ADC_CHANNEL_4",
        "",
        "/* misc */",
        f"#define PIN_WS2812     {gpio_num(p['WS2812'])}",
        f"#define PIN_CAM_PWDN   {gpio_num(p['CAM_PWDN'])}",
        f"#define PIN_EXP_IO     {gpio_num(p['EXP_IO'])}",
        "",
        "/* SDIO link to ESP32-C6 (esp-hosted) — also set in sdkconfig */",
        f"#define PIN_SDIO_CLK   {gpio_num(p['SDIO_CLK'])}",
        f"#define PIN_SDIO_CMD   {gpio_num(p['SDIO_CMD'])}",
        f"#define PIN_SDIO_D0    {gpio_num(p['SDIO_D0'])}",
        f"#define PIN_SDIO_D1    {gpio_num(p['SDIO_D1'])}",
        f"#define PIN_SDIO_D2    {gpio_num(p['SDIO_D2'])}",
        f"#define PIN_SDIO_D3    {gpio_num(p['SDIO_D3'])}",
        f"#define PIN_C6_EN      {gpio_num(p['C6_EN'])}",
        "",
        "/* UART0 console + BOOT strap (VERIFY against ESP32-P4 datasheet) */",
        f"#define PIN_UART0_TX   {gpio_num(p['UART0_TX'])}",
        f"#define PIN_UART0_RX   {gpio_num(p['UART0_RX'])}",
        f"#define PIN_BOOT_STRAP {gpio_num(p['BOOT_STRAP'])}",
        "",
        "#endif",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
