M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon Jun 22 08:33:37 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-22T08:33:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X3.0Y-26.71
X3.0Y-32.49
T2
X5.0Y-5.0
X5.0Y-69.0
X33.0Y-5.0
X33.0Y-69.0
M30
