M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat Jun 13 08:25:09 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-13T08:25:09+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X18.11Y-36.9
X23.89Y-36.9
T2
X3.0Y-3.0
X3.0Y-39.0
X39.0Y-3.0
X39.0Y-39.0
M30
