M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sun Jun 14 01:09:49 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-14T01:09:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X0.9Y-21.11
X0.9Y-26.89
T2
X4.0Y-4.0
X4.0Y-62.0
X28.0Y-4.0
X28.0Y-62.0
M30
