#!/usr/bin/env python3
"""Generate the firmware board_pinmap_tinyhoop.h from design.PINMAP.

design.py is the single source of truth for the pin assignment; this writes
the header the TinyHoop firmware build consumes (selected by
-DSTRATOS_BOARD_TINYHOOP). Edit design.py, re-run, commit both.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
OUT = os.path.join(REPO, "firmware", "components", "board", "include",
                   "board_pinmap_tinyhoop.h")

sys.path.insert(0, HERE)
import design  # noqa: E402


def g(sig):
    return int(design.PINMAP[sig].replace("GPIO", ""))


def main():
    L = [
        "/* board_pinmap_tinyhoop.h — GENERATED by hardware/pcb_tinyhoop/scripts/",
        " * gen_pinmap.py (committed copy). Mirrors the STRATOS TINYHOOP AIO net",
        " * assignment (design.py PINMAP). Do not edit by hand.",
        " * SPDX-License-Identifier: MIT */",
        "#ifndef BOARD_PINMAP_TINYHOOP_H",
        "#define BOARD_PINMAP_TINYHOOP_H",
        "",
        "/* SPI bus (ICM-42688-P + PMW3901 + SX1262) */",
        f"#define PIN_SPI_SCLK   {g('SPI_SCLK')}",
        f"#define PIN_SPI_MOSI   {g('SPI_MOSI')}",
        f"#define PIN_SPI_MISO   {g('SPI_MISO')}",
        f"#define PIN_CS_IMU     {g('CS_IMU')}",
        f"#define PIN_CS_FLOW    {g('CS_FLOW')}",
        f"#define PIN_IMU_INT    {g('IMU_INT')}",
        "",
        "/* I2C bus (SPL06-001 0x76, VL53L1X 0x29) */",
        f"#define PIN_I2C_SDA    {g('I2C_SDA')}",
        f"#define PIN_I2C_SCL    {g('I2C_SCL')}",
        f"#define PIN_VL53_XSHUT {g('VL53_XSHUT')}",
        "",
        "/* motors (M1 FR, M2 BR, M3 BL, M4 FL) — DShot600 to the 4 ESC drivers */",
        f"#define PIN_MOTOR_1    {g('MOTOR_1')}",
        f"#define PIN_MOTOR_2    {g('MOTOR_2')}",
        f"#define PIN_MOTOR_3    {g('MOTOR_3')}",
        f"#define PIN_MOTOR_4    {g('MOTOR_4')}",
        "",
        "/* CRSF (ExpressLRS RX on the 3-pin socket, 420 kbaud 8N1) */",
        f"#define PIN_CRSF_TX    {g('CRSF_TX')}",
        f"#define PIN_CRSF_RX    {g('CRSF_RX')}",
        "",
        "/* SX1262 LoRa (shared SPI2 + dedicated control pins; module optional) */",
        f"#define PIN_LORA_CS    {g('LORA_CS')}",
        f"#define PIN_LORA_BUSY  {g('LORA_BUSY')}",
        f"#define PIN_LORA_DIO1  {g('LORA_DIO1')}",
        f"#define PIN_LORA_RST   {g('LORA_RST')}",
        "",
        "/* GPS / compass connector J15 (UART + shares the I2C bus) */",
        f"#define PIN_GPS_TX     {g('GPS_TX')}   /* P4 TX -> GPS RX */",
        f"#define PIN_GPS_RX     {g('GPS_RX')}",
        "",
        "/* battery sense: 2S-3S, 400k/100k divider => /5 (VERIFY ADC channel) */",
        f"#define PIN_VBAT_ADC     {g('VBAT_ADC')}",
        "#define VBAT_ADC_UNIT    ADC_UNIT_1",
        "#define VBAT_ADC_CHANNEL ADC_CHANNEL_4",
        "#define VBAT_DIVIDER     5.0f",
        "",
        "/* misc */",
        f"#define PIN_WS2812     {g('WS2812')}",
        f"#define PIN_CAM_PWDN   {g('CAM_PWDN')}",
        f"#define PIN_VTX_SA     {g('VTX_SA')}    /* SmartAudio (half-duplex UART) to the VTX bay */",
        "",
        "/* SDIO link to ESP32-C6 (esp-hosted) */",
        f"#define PIN_SDIO_CLK   {g('SDIO_CLK')}",
        f"#define PIN_SDIO_CMD   {g('SDIO_CMD')}",
        f"#define PIN_SDIO_D0    {g('SDIO_D0')}",
        f"#define PIN_SDIO_D1    {g('SDIO_D1')}",
        f"#define PIN_SDIO_D2    {g('SDIO_D2')}",
        f"#define PIN_SDIO_D3    {g('SDIO_D3')}",
        f"#define PIN_C6_EN      {g('C6_EN')}",
        "",
        "/* UART0 console + BOOT strap */",
        f"#define PIN_UART0_TX   {g('UART0_TX')}",
        f"#define PIN_UART0_RX   {g('UART0_RX')}",
        f"#define PIN_BOOT_STRAP {g('BOOT_STRAP')}",
        "",
        "#endif",
        "",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
