/* board_pinmap_tinyhoop.h — GENERATED by hardware/pcb_tinyhoop/scripts/
 * gen_pinmap.py (committed copy). Mirrors the STRATOS TINYHOOP AIO net
 * assignment (design.py PINMAP). Do not edit by hand.
 * SPDX-License-Identifier: MIT */
#ifndef BOARD_PINMAP_TINYHOOP_H
#define BOARD_PINMAP_TINYHOOP_H

/* SPI bus (ICM-42688-P + PMW3901 + SX1262) */
#define PIN_SPI_SCLK   9
#define PIN_SPI_MOSI   10
#define PIN_SPI_MISO   11
#define PIN_CS_IMU     12
#define PIN_CS_FLOW    13
#define PIN_IMU_INT    21

/* I2C bus (SPL06-001 0x76, VL53L1X 0x29) */
#define PIN_I2C_SDA    7
#define PIN_I2C_SCL    8
#define PIN_VL53_XSHUT 23

/* motors (M1 FR, M2 BR, M3 BL, M4 FL) — DShot600 to the 4 ESC drivers */
#define PIN_MOTOR_1    45
#define PIN_MOTOR_2    46
#define PIN_MOTOR_3    47
#define PIN_MOTOR_4    48

/* CRSF (ExpressLRS RX on the 3-pin socket, 420 kbaud 8N1) */
#define PIN_CRSF_TX    4
#define PIN_CRSF_RX    5

/* SX1262 LoRa (shared SPI2 + dedicated control pins; module optional) */
#define PIN_LORA_CS    26
#define PIN_LORA_BUSY  27
#define PIN_LORA_DIO1  28
#define PIN_LORA_RST   29

/* GPS / compass connector J15 (UART + shares the I2C bus) */
#define PIN_GPS_TX     30   /* P4 TX -> GPS RX */
#define PIN_GPS_RX     31

/* battery sense: 2S-3S, 400k/100k divider => /5 (VERIFY ADC channel) */
#define PIN_VBAT_ADC     20
#define VBAT_ADC_UNIT    ADC_UNIT_1
#define VBAT_ADC_CHANNEL ADC_CHANNEL_4
#define VBAT_DIVIDER     5.0f

/* misc */
#define PIN_WS2812     24
#define PIN_CAM_PWDN   25
#define PIN_VTX_SA     6    /* SmartAudio (half-duplex UART) to the VTX bay */

/* SDIO link to ESP32-C6 (esp-hosted) */
#define PIN_SDIO_CLK   18
#define PIN_SDIO_CMD   19
#define PIN_SDIO_D0    14
#define PIN_SDIO_D1    15
#define PIN_SDIO_D2    16
#define PIN_SDIO_D3    17
#define PIN_C6_EN      54

/* UART0 console + BOOT strap */
#define PIN_UART0_TX   37
#define PIN_UART0_RX   38
#define PIN_BOOT_STRAP 35

#endif
